<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="fa" sourcelanguage="en">
<context>
    <name>MainWindow</name>
    <message>
        <source>Human Aided Design</source>
        <translation>طراحی به کمک انسان</translation>
    </message>
    <message>
        <source>Presentation</source>
        <translation>ارائه</translation>
    </message>
    <message>
        <source>Noraml</source>
        <translation>معمولی</translation>
    </message>
    <message>
        <source>Feasibles</source>
        <translation>قابل قبول</translation>
    </message>
    <message>
        <source>Selected</source>
        <translation>منتخب</translation>
    </message>
    <message>
        <source>Show</source>
        <translation>نمایش</translation>
    </message>
    <message>
        <source>Feasible</source>
        <translation>ممکن</translation>
    </message>
    <message>
        <source>Run</source>
        <translation>اجرا</translation>
    </message>
    <message>
        <source>Seed</source>
        <translation>شروع</translation>
    </message>
    <message>
        <source>Execute</source>
        <translation>محاسبه</translation>
    </message>
    <message>
        <source>Load</source>
        <translation>بارگذاری</translation>
    </message>
    <message>
        <source>Ok</source>
        <translation>تایید</translation>
    </message>
    <message>
        <source>Penalties</source>
        <translation>جریمه‌ها</translation>
    </message>
    <message>
        <source>Sum</source>
        <translation>مجموع</translation>
    </message>
    <message>
        <source>Area</source>
        <translation>مساحت</translation>
    </message>
    <message>
        <source>Intersection</source>
        <translation>تداخل</translation>
    </message>
    <message>
        <source>Side</source>
        <translation>حاشیه</translation>
    </message>
    <message>
        <source>Access</source>
        <translation>دسترسی</translation>
    </message>
    <message>
        <source>Light</source>
        <translation>نور</translation>
    </message>
    <message>
        <source>Space</source>
        <translation>فضا</translation>
    </message>
    <message>
        <source>Genome</source>
        <translation>ژنوم</translation>
    </message>
    <message>
        <source>Image</source>
        <translation>تصویر</translation>
    </message>
</context>
<context>
    <name>PlanViewer</name>
    <message>
        <source>kitchen</source>
        <translation>آشپزخانه</translation>
    </message>
    <message>
        <source>bedroom</source>
        <translation>خواب</translation>
    </message>
    <message>
        <source>bathroom</source>
        <translation>حمام</translation>
    </message>
    <message>
        <source>toilet</source>
        <translation>دستشویی</translation>
    </message>
    <message>
        <source>stairs</source>
        <translation>راه‌پله</translation>
    </message>
    <message>
        <source>elevator</source>
        <translation>آسانسور</translation>
    </message>
</context>
</TS>
